config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index'
  get 'carts/show'
  get 'carts/add_item'
  get 'carts/update_item'
  get 'carts/remove_item'
  get 'carts/checkout'
  root 'products#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  resources :orders
  resources :products
  resources :sellers
  resources :buyers
  resources :users

  resource :cart, only: [:show] do
    post 'add/:product_id', to: 'carts#add_item', as: 'add_item'
    patch 'update_item/:product_id', to: 'carts#update_item', as: 'update_item'
    delete 'remove_item/:product_id', to: 'carts#remove_item', as: 'remove_item'
  end

  post '/checkout', to: 'carts#checkout'
  get "/dashboard", to: "dashboards#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_one :buyer, dependent: :destroy
  has_one :seller, dependent: :destroy, required: false
  has_many :orders, through: :buyer
  has_one :cart, dependent: :destroy

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true, length: { minimum: 6 }, confirmation: true

  after_create :create_buyer_account_and_cart

  private

  def create_buyer_account_and_cart
    create_buyer
    create_cart
  end
end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_user, only: [:index, :show]

    def index
      @users = User.all
    end

    def show
      @user = User.find(params[:id])
    end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.create_seller if params[:user][:seller] == "1"
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Account created successfully.'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :seller)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="mb-4">
      <h2 class="text-red-600"><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li class="text-red-600"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :email, class: "block text-gray-700" %>
    <%= form.email_field :email, class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm" %>
  </div>

  <div class="mb-4">
    <%= form.label :password, class: "block text-gray-700" %>
    <%= form.password_field :password, class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm" %>
  </div>

  <div class="mb-4">
    <%= form.label :password_confirmation, class: "block text-gray-700" %>
    <%= form.password_field :password_confirmation, class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm" %>
  </div>

  <div class="mb-4">
    <%= form.label :seller, class: "block text-gray-700" %>
    <%= form.check_box :seller, class: "mt-1" %>
  </div>

  <div class="mb-4">
    <%= form.submit class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td class="px-6 py-4 whitespace-nowrap">
    <div class="text-sm text-gray-900"><%= user.id %></div>
  </td>
  <td class="px-6 py-4 whitespace-nowrap">
    <div class="text-sm text-gray-900"><%= user.email %></div>
  </td>
  <td class="px-6 py-4 whitespace-nowrap">
    <%= link_to 'Show', user_path(user), class: "text-blue-600 hover:text-blue-900" %>
    <%= link_to 'Edit', edit_user_path(user), class: "text-green-600 hover:text-green-900 ml-2" %>
    <%= link_to 'Destroy', user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: "text-red-600 hover:text-red-900 ml-2" %>
  </td>
</tr>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h1 class="text-3xl font-bold mb-4">Users</h1>

<table class="min-w-full divide-y divide-gray-200">
  <thead class="bg-gray-50">
  <tr>
    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">ID</th>
    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Email</th>
    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
  </tr>
  </thead>
  <tbody class="bg-white divide-y divide-gray-200">
  <%= render partial: 'user', collection: @users %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="min-h-screen flex items-center justify-center bg-gray-100">
  <div class="bg-white p-8 rounded-lg shadow-md w-full max-w-md">
    <h2 class="text-2xl font-bold mb-4 text-gray-800">Register</h2>

    <%= form_with(model: @user, url: register_path, local: true) do |form| %>
      <% if @user.errors.any? %>
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4">
          <strong class="font-bold"><%= pluralize(@user.errors.count, "error") %>:</strong>
          <ul class="mt-1">
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-4">
        <%= form.label :email, class: "block text-gray-700" %>
        <%= form.email_field :email, autofocus: true, required: true, class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm" %>
      </div>

      <div class="mb-4">
        <%= form.label :password, class: "block text-gray-700" %>
        <%= form.password_field :password, required: true, class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm" %>
      </div>

      <div class="mb-4">
        <%= form.label :password_confirmation, class: "block text-gray-700" %>
        <%= form.password_field :password_confirmation, required: true, class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm" %>
      </div>

      <div class="mb-4 flex items-center">
        <%= form.label :seller, class: "block text-gray-700 mr-2" %>
        <%= form.check_box :seller, class: "mt-1" %>
        <span class="text-gray-700">Register as Seller</span>
      </div>

      <div class="mb-4 flex items-center justify-between">
        <%= form.submit "Register", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
        <%= link_to "Login", login_path, class: "text-blue-500 hover:text-blue-700" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>