config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index'
  get 'carts/show'
  get 'carts/add_item'
  get 'carts/update_item'
  get 'carts/remove_item'
  get 'carts/checkout'
  root 'products#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  resources :orders
  resources :products
  resources :sellers
  resources :buyers
  resources :users

  resource :cart, only: [:show] do
    post 'add/:product_id', to: 'carts#add_item', as: 'add_item'
    patch 'update_item/:product_id', to: 'carts#update_item', as: 'update_item'
    delete 'remove_item/:product_id', to: 'carts#remove_item', as: 'remove_item'
  end

  post '/checkout', to: 'carts#checkout'
  get "/dashboard", to: "dashboards#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :require_user
  before_action :set_cart

  def show
  end

  def add_item
    product = Product.find(params[:product_id])
    if product.stock < params[:quantity].to_i
      redirect_to product_path(product), alert: "Not enough stock available."
      return
    end

    @cart_item = @cart.cart_items.find_or_initialize_by(product: product)
    @cart_item.quantity ||= 0
    @cart_item.quantity += params[:quantity].to_i

    if @cart_item.save
      redirect_to cart_path, notice: "#{product.name} was added to your cart."
    else
      redirect_to product_path(product), alert: "Could not add product to cart."
    end
  end

  def update_item
    product = Product.find(params[:product_id])
    if product.stock < params[:quantity].to_i
      redirect_to cart_path, alert: "Not enough stock available."
      return
    end

    @cart_item = @cart.cart_items.find_by(product: product)
    @cart_item.quantity = params[:quantity].to_i

    if @cart_item.save
      redirect_to cart_path, notice: "Cart item updated."
    else
      redirect_to cart_path, alert: "Could not update cart item."
    end
  end

  def remove_item
    product = Product.find(params[:product_id])
    @cart_item = @cart.cart_items.find_by(product: product)

    if @cart_item.destroy
      redirect_to cart_path, notice: "Product removed from cart."
    else
      redirect_to cart_path, alert: "Could not remove product from cart."
    end
  end

  def checkout
    ActiveRecord::Base.transaction do
      order = current_user.buyer.orders.create!(total_price: 0)
      @cart.cart_items.each do |cart_item|
        order.order_items.create!(
          product: cart_item.product,
          quantity: cart_item.quantity,
          total_price: cart_item.product.price * cart_item.quantity
        )
      end
      @cart.cart_items.destroy_all
      order.save!
    end

    redirect_to orders_path, notice: "Order successfully created."
  end

  private

  def set_cart
    @cart = current_user.cart || current_user.create_cart
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_item.html.erb
<tr>
  <td class="px-6 py-4 whitespace-nowrap"><%= cart_item.product.name %></td>
  <td class="px-6 py-4 whitespace-nowrap">
    <%= form_with url: update_item_cart_path(cart_item.product), method: :patch, local: true do |form| %>
      <%= form.number_field :quantity, value: cart_item.quantity, min: 1, class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm" %>
      <%= form.submit "Update", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded ml-2" %>
    <% end %>
  </td>
  <td class="px-6 py-4 whitespace-nowrap"><%= number_to_currency(cart_item.product.price * cart_item.quantity) %></td>
  <td class="px-6 py-4 whitespace-nowrap">
    <%= link_to 'Remove', remove_item_cart_path(cart_item.product), method: :delete, data: { confirm: 'Are you sure?' }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
  </td>
</tr>

app/views/carts/add_item.html.erb
<h1>Carts#add_item</h1>
<p>Find me in app/views/carts/add_item.html.erb</p>

app/views/carts/checkout.html.erb
<h1>Carts#checkout</h1>
<p>Find me in app/views/carts/checkout.html.erb</p>

app/views/carts/remove_item.html.erb
<h1>Carts#remove_item</h1>
<p>Find me in app/views/carts/remove_item.html.erb</p>

app/views/carts/show.html.erb
<h1 class="text-3xl font-bold mb-4">Your Cart</h1>

<% if @cart && @cart.cart_items.any? %>
  <div class="bg-white shadow-md rounded-lg p-6">
    <table class="min-w-full divide-y divide-gray-200">
      <thead>
      <tr>
        <th class="px-6 py-3 bg-gray-50">Product</th>
        <th class="px-6 py-3 bg-gray-50">Quantity</th>
        <th class="px-6 py-3 bg-gray-50">Total Price</th>
        <th class="px-6 py-3 bg-gray-50">Actions</th>
      </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
      <% @cart.cart_items.each do |cart_item| %>
        <%= render 'cart_item', cart_item: cart_item %>
      <% end %>
      </tbody>
    </table>
    <div class="flex justify-end mt-4">
      <%= button_to 'Checkout', checkout_path, method: :post, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" %>
    </div>
  </div>
<% else %>
  <p>Your cart is empty.</p>
<% end %>

<%= link_to 'Back to Products', products_path, class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded mt-4 inline-block" %>

app/views/carts/update_item.html.erb
<h1>Carts#update_item</h1>
<p>Find me in app/views/carts/update_item.html.erb</p>