config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index'
  get 'carts/show'
  get 'carts/add_item'
  get 'carts/update_item'
  get 'carts/remove_item'
  get 'carts/checkout'
  root 'products#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  resources :orders
  resources :products
  resources :sellers
  resources :buyers
  resources :users

  resource :cart, only: [:show] do
    post 'add/:product_id', to: 'carts#add_item', as: 'add_item'
    patch 'update_item/:product_id', to: 'carts#update_item', as: 'update_item'
    delete 'remove_item/:product_id', to: 'carts#remove_item', as: 'remove_item'
  end

  post '/checkout', to: 'carts#checkout'
  get "/dashboard", to: "dashboards#index"
end

app/models/product.rb
# app/models/product.rb
class Product < ApplicationRecord
  belongs_to :seller

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :stock, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_user, except: %i[index show]
  before_action :require_seller, only: %i[new create edit update destroy]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = current_user.seller.products.build
  end

  def create
    @product = current_user.seller.products.build(product_params)

    if @product.save
      redirect_to @product, notice: "Product was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product, notice: "Product was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url, notice: "Product was successfully destroyed."
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="bg-white shadow-md rounded-lg p-6">
  <%= form_with(model: product, local: true) do |form| %>
    <% if product.errors.any? %>
      <div id="error_explanation" class="mb-4">
        <h2 class="text-red-600"><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
        <ul>
          <% product.errors.full_messages.each do |message| %>
            <li class="text-red-600"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-4">
      <%= form.label :name, class: "block text-gray-700" %>
      <%= form.text_field :name, class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm" %>
    </div>

    <div class="mb-4">
      <%= form.label :description, class: "block text-gray-700" %>
      <%= form.text_area :description, class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm" %>
    </div>

    <div class="mb-4">
      <%= form.label :price, class: "block text-gray-700" %>
      <%= form.number_field :price, step: 0.01, class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm" %>
    </div>

    <div class="mb-4">
      <%= form.label :stock, class: "block text-gray-700" %>
      <%= form.number_field :stock, class: "mt-1 block w-full border-gray-300 rounded-md shadow-sm" %>
    </div>

    <div class="mb-4">
      <%= form.submit class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    </div>
  <% end %>
</div>

app/views/products/_product.html.erb
<tr>
  <td class="px-6 py-4 whitespace-nowrap"><%= product.name %></td>
  <td class="px-6 py-4 whitespace-nowrap"><%= product.description %></td>
  <td class="px-6 py-4 whitespace-nowrap"><%= product.price %></td>
  <td class="px-6 py-4 whitespace-nowrap"><%= product.stock %></td>
  <td class="px-6 py-4 whitespace-nowrap">
    <%= link_to 'Show', product_path(product), class: "text-indigo-600 hover:text-indigo-900" %>
    <%= link_to 'Edit', edit_product_path(product), class: "text-indigo-600 hover:text-indigo-900 ml-2" %>
    <%= link_to 'Delete', product_path(product), method: :delete, data: { confirm: 'Are you sure?' }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded ml-2" %>
  </td>
</tr>

app/views/products/_product_card.html.erb
<!-- app/views/products/_product_card.html.erb -->
<div class="w-full sm:w-1/2 md:w-1/2 xl:w-1/4 p-4">
  <div class="c-card block bg-white shadow-md hover:shadow-xl rounded-lg overflow-hidden">
    <div class="relative pb-48 overflow-hidden">
      <img class="absolute inset-0 h-full w-full object-cover" src="https://source.unsplash.com/random/300x300" alt="<%= product.name %>">
    </div>
    <div class="p-4">
      <span class="inline-block px-2 py-1 leading-none bg-orange-200 text-orange-800 rounded-full font-semibold uppercase tracking-wide text-xs">New</span>
      <h2 class="mt-2 mb-2 font-bold"><%= product.name %></h2>
      <p class="text-sm"><%= product.description %></p>
      <div class="mt-3 flex items-center">
        <span class="text-sm font-semibold">Price:</span>&nbsp;<span class="font-bold text-xl"><%= number_to_currency(product.price) %></span>
      </div>
      <div class="mt-3 flex items-center">
        <span class="text-sm font-semibold">Stock:</span>&nbsp;<span class="text-gray-700"><%= product.stock %></span>
      </div>
    </div>
    <div class="p-4 border-t border-b text-xs text-gray-700">
      <span class="flex items-center mb-1">
        <i class="far fa-clock fa-fw mr-2 text-gray-900"></i> Available
      </span>
    </div>
    <div class="p-4 flex items-center text-sm text-gray-600">
      <%= form_with url: add_item_cart_path(product), method: :post, local: true do %>
        <div class="flex items-center">
          <%= number_field_tag :quantity, 1, min: 1, max: product.stock, class: "mt-1 block w-20 border-gray-300 rounded-md shadow-sm" %>
          <%= submit_tag 'Add to Cart', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded ml-2" %>
        </div>
      <% end %>
    </div>
    <div class="p-4 flex justify-between items-center text-sm text-gray-600">
      <%= link_to 'Edit', edit_product_path(product), class: "bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded" %>
      <%= button_to 'Delete', product_path(product), method: :delete, data: { confirm: 'Are you sure?' }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<!-- app/views/products/index.html.erb -->
<h1 class="text-3xl font-bold mb-4">Products</h1>

<% if logged_in? && current_user.seller %>
  <%= link_to 'New Product', new_product_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-4 inline-block" %>
<% end %>

<div class="container mx-auto">
  <div class="flex flex-wrap -mx-4">
    <% @products.each_with_index do |product, index| %>
      <div class="w-full sm:w-1/2 md:w-1/2 xl:w-1/4 p-4">
        <div class="c-card block bg-white shadow-md hover:shadow-xl rounded-lg overflow-hidden">
          <div class="relative pb-48 overflow-hidden">
            <img class="absolute inset-0 h-full w-full object-cover" src="https://source.unsplash.com/random/300x300?sig=<%= index %>" alt="<%= product.name %>">
          </div>
          <div class="p-4">
            <span class="inline-block px-2 py-1 leading-none bg-orange-200 text-orange-800 rounded-full font-semibold uppercase tracking-wide text-xs">New</span>
            <h2 class="mt-2 mb-2 font-bold text-2xl"><%= product.name %></h2>
            <p class="text-sm"><%= product.description %></p>
            <div class="mt-3 flex items-center">
              <span class="text-sm font-semibold">Price:</span>&nbsp;<span class="font-bold text-xl"><%= number_to_currency(product.price) %></span>
            </div>
            <div class="mt-3 flex items-center">
              <span class="text-sm font-semibold">Stock:</span>&nbsp;<span class="text-gray-700"><%= product.stock %></span>
            </div>
            <div class="mt-4 flex justify-between items-center">
              <%= link_to 'Show', product_path(product), class: "text-blue-500 hover:text-blue-700" %>
              <% if logged_in? && current_user.seller %>
                <%= link_to 'Edit', edit_product_path(product), class: "text-blue-500 hover:text-blue-700 ml-2" %>
                <%= link_to 'Delete', product_path(product), method: :delete, data: { confirm: 'Are you sure?' }, class: "text-red-500 hover:text-red-700 ml-2" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<!-- app/views/products/show.html.erb -->
<h1 class="text-3xl font-bold mb-4"><%= @product.name %></h1>
<div class="c-card block bg-white shadow-md hover:shadow-xl rounded-lg overflow-hidden">
  <div class="relative pb-48 overflow-hidden">
    <img class="absolute inset-0 h-full w-full object-cover" src="https://source.unsplash.com/random/300x300?sig=<%= @product.id %>" alt="<%= @product.name %>">
  </div>
  <div class="p-4">
    <p class="text-gray-700 mb-2"><%= @product.description %></p>
    <p class="text-gray-900 font-semibold"><%= number_to_currency(@product.price) %></p>
    <p class="text-gray-700 mb-4">Stock: <%= @product.stock %></p>
    <%= form_with url: add_item_cart_path(@product), method: :post, local: true do %>
      <div class="flex items-center">
        <%= number_field_tag :quantity, 1, min: 1, max: @product.stock, class: "mt-1 block w-20 border-gray-300 rounded-md shadow-sm" %>
        <%= submit_tag 'Add to Cart', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded ml-2" %>
      </div>
    <% end %>
  </div>
  <div class="flex justify-between items-center mt-4">
    <%= link_to 'Back to Products', products_path, class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded" %>
    <%= link_to 'Edit', edit_product_path(@product), class: "bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded ml-2" %>
    <%= button_to 'Destroy', product_path(@product), method: :delete, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded ml-2" %>
  </div>
</div>