config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index'
  get 'carts/show'
  get 'carts/add_item'
  get 'carts/update_item'
  get 'carts/remove_item'
  get 'carts/checkout'
  root 'products#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  resources :orders
  resources :products
  resources :sellers
  resources :buyers
  resources :users

  resource :cart, only: [:show] do
    post 'add/:product_id', to: 'carts#add_item', as: 'add_item'
    patch 'update_item/:product_id', to: 'carts#update_item', as: 'update_item'
    delete 'remove_item/:product_id', to: 'carts#remove_item', as: 'remove_item'
  end

  post '/checkout', to: 'carts#checkout'
  get "/dashboard", to: "dashboards#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buyer.rb
# app/models/buyer.rb
class Buyer < ApplicationRecord
  belongs_to :user
  has_many :orders
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :buyer
  has_many :order_items, dependent: :destroy

  validates :total_price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  before_save :set_total_price

  def set_total_price
    self.total_price = order_items.sum('quantity * total_price')
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :total_price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  before_save :set_total_price

  private

  def set_total_price
    self.total_price = self.quantity * self.product.price
  end
end

app/models/product.rb
# app/models/product.rb
class Product < ApplicationRecord
  belongs_to :seller

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :stock, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/seller.rb
# app/models/seller.rb
class Seller < ApplicationRecord
  belongs_to :user
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_one :buyer, dependent: :destroy
  has_one :seller, dependent: :destroy, required: false
  has_many :orders, through: :buyer
  has_one :cart, dependent: :destroy

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true, length: { minimum: 6 }, confirmation: true

  after_create :create_buyer_account_and_cart

  private

  def create_buyer_account_and_cart
    create_buyer
    create_cart
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :require_user
  before_action :set_cart

  def show
  end

  def add_item
    product = Product.find(params[:product_id])
    if product.stock < params[:quantity].to_i
      redirect_to product_path(product), alert: "Not enough stock available."
      return
    end

    @cart_item = @cart.cart_items.find_or_initialize_by(product: product)
    @cart_item.quantity ||= 0
    @cart_item.quantity += params[:quantity].to_i

    if @cart_item.save
      redirect_to cart_path, notice: "#{product.name} was added to your cart."
    else
      redirect_to product_path(product), alert: "Could not add product to cart."
    end
  end

  def update_item
    product = Product.find(params[:product_id])
    if product.stock < params[:quantity].to_i
      redirect_to cart_path, alert: "Not enough stock available."
      return
    end

    @cart_item = @cart.cart_items.find_by(product: product)
    @cart_item.quantity = params[:quantity].to_i

    if @cart_item.save
      redirect_to cart_path, notice: "Cart item updated."
    else
      redirect_to cart_path, alert: "Could not update cart item."
    end
  end

  def remove_item
    product = Product.find(params[:product_id])
    @cart_item = @cart.cart_items.find_by(product: product)

    if @cart_item.destroy
      redirect_to cart_path, notice: "Product removed from cart."
    else
      redirect_to cart_path, alert: "Could not remove product from cart."
    end
  end

  def checkout
    ActiveRecord::Base.transaction do
      order = current_user.buyer.orders.create!(total_price: 0)
      @cart.cart_items.each do |cart_item|
        order.order_items.create!(
          product: cart_item.product,
          quantity: cart_item.quantity,
          total_price: cart_item.product.price * cart_item.quantity
        )
      end
      @cart.cart_items.destroy_all
      order.save!
    end

    redirect_to orders_path, notice: "Order successfully created."
  end

  private

  def set_cart
    @cart = current_user.cart || current_user.create_cart
  end
end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_user, only: [:index, :show]

    def index
      @users = User.all
    end

    def show
      @user = User.find(params[:id])
    end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.create_seller if params[:user][:seller] == "1"
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Account created successfully.'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :seller)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/sessions_helper.rb
# app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amazon</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload" %>

  <!-- Ajouter le lien CDN de Tailwind CSS ici -->
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>

<body class="bg-gray-100 text-gray-800">
<nav class="bg-gray-800 p-4 text-white">
  <div class="container mx-auto flex justify-between items-center">
    <div class="flex items-center space-x-4">
      <%= link_to 'Amazon', root_path, class: "text-2xl font-bold" %>
      <%= link_to 'Products', products_path, class: "hover:underline" %>
      <% if logged_in? %>
        <%= link_to 'Dashboard', dashboard_path, class: "hover:underline" %>
        <%= link_to 'Orders', orders_path, class: "hover:underline" %>
        <%= link_to 'Cart', cart_path, class: "hover:underline" %>
      <% end %>
    </div>
    <div class="flex items-center space-x-4">
      <% if logged_in? %>
        <span class="mr-2">Logged in as <%= current_user.email %></span>
        <%= button_to 'Logout', logout_path, method: :delete, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
      <% else %>
        <%= link_to 'Login', login_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
        <%= link_to 'Register', register_path, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" %>
      <% end %>
    </div>
  </div>
</nav>
<div class="container mx-auto mt-4">
  <%= yield %>
</div>
</body>
</html>